### ISSUE TITLE
Can't upload file from file picker on tiling window manager.

### ISSUE THREAD

**Issue by FedeAbella** [rafatosta/zapzap#281]
Hi there! I'm aware of #74, but didn't want to reopen such an old issue. Also, the proposed solution on #74 is not working. I have `xdg-desktop-portal-gtk` installed, and still cannot upload files when using the file picker.

Here's a recording, if it helps:

https://github.com/user-attachments/assets/9456cabc-297c-474b-a105-623374e14b70

Let me know what other info I can get you

**Comment by rafatosta** [comment]
Please disable tilling and try again and see if it works. 

I remember that this was a problem with this extension and not with Zapzap, but please confirm.

**Comment by rafatosta** [comment]
Please disable tilling and try again and see if it works. 

I remember that this was a problem with this extension and not with Zapzap, but please confirm.

**Comment by FedeAbella** [comment]
Tiling is not something you can really _disable_ in Hyprland, it's a tiling compositor. You **can** make a window floating (which is the exception) and in that case, upload does work. But this is not an extension, it's a compositor, and other flatpak apps don't fail to add files from the file picker when tiled.

**Comment by rafatosta** [comment]
In version 6.0 Beta, I implemented an option **not to use Native File Dialog** . See if it works for you, please.

![Image](https://github.com/user-attachments/assets/e1bd79d0-3ebd-441c-8a1f-56f1954776ef)

I am sending the version now, so in a few hours it will be available in flathub-beta. See #282

**Comment by FedeAbella** [comment]
Sorry, it's been a busy couple of days. Turning that option on in the new Beta version still shows the native file picker for me. Like, there is no difference between having the checkbox on or off. Should I be on the lookout for something else?

Also, using the native file picker, regardless of whether the checkbox is on or not, behaves the same as the old version: still the file doesn't appear. And dragging from another window also still works.

**Comment by FedeAbella** [comment]
I don't know if this is of any use but: Hyprland suggests a `.config/xdg-desktop-portal/hyprland-portals.conf` configuration for using the KDE plasma native file picker, which is:
```conf
[preferred]
default = hyprland;gtk
org.freedesktop.impl.portal.FileChooser = kde
org.freedesktop.impl.portal.AppChooser=kde
```

I tried commenting out the `FileChooser` one, which meant another file picker loaded up (not sure which one), but the behaviour was still the same:
- No file received by ZapZap
- The settings checkbox did not change the file picker

**Comment by jultty** [comment]
I was having a similar issue with ZapZap 6.0 from Flatpak on Niri 25.02, Alpine 3.21.3. After restarting and toggling "Don't use a platform-native file dialog", I could save files normally.

After saving, the screen would freeze, both the WhatsApp UI and the outer ZapZap UI. Choosing "Settings" from the tray menu right-click did bring up the settings screen, but it still did not respond to input. There was no console output either. Setting ZapZap to float did not have any effect, neither did swapping xdg-desktop-portal-gtk and xdg-desktop-portal-gnome.

**Comment by rafatosta** [comment]
Does this problem persist?

**Comment by FedeAbella** [comment]
I've personally moved to another client. I can tell you I experienced something similar while trying other clients, but with slight differences. Sometimes the upload would work if the app was floating and the file chooser not. Sometimes the other way around. I'm pretty sure the client I'm using now only works if the file chooser floats but not the app. 

It never worked if both the app and the file chooser were tiled. At this point I'm assuming it must be something to do with electron.

**Comment by rafatosta** [comment]
Thanks for the feedback. 

ZapZap does not use Electron, it is developed with the Qt framework.
