### ISSUE TITLE
Spellcheck giving false positives

### ISSUE THREAD

**Issue by dymdipii** [rafatosta/zapzap#287]
I'm using the spellchecker functionality but it's giving me false positives. Attached are my spellchecker settings and examples of the issue.

![Example 1](https://github.com/user-attachments/assets/70769571-6713-4400-aec3-5a0cee09758c)
![Example 2](https://github.com/user-attachments/assets/57ad00df-c164-4d00-ae16-60c366800061)
![Example 3](https://github.com/user-attachments/assets/43a652b5-e233-4e9c-85f3-d7e08d9576f0)

![ZapZap Settings](https://github.com/user-attachments/assets/7e915ca1-3e6d-491b-8657-79942c4f7c96)

**Comment by rafatosta** [comment]
See the new functionality implemented: Spell checking for multiple languages #295

6.0 beta in #282 

Check if the error still continues in version 6.0 Beta, please.

**Comment by dymdipii** [comment]
I just installed the 6.0 beta and I'm still seeing the same issue:

![Image](https://github.com/user-attachments/assets/f0c7d7f5-4349-45c5-ad57-c77c861ea897)

I'm still using the en_GB dictionary and that dictionary is definitely present in the "/run/host/usr/share/qt6/qtwebengine_dictionaries/" directory. Let me know if there are any specific tests that you'd like me to run.

**Comment by rafatosta** [comment]
> I just installed the 6.0 beta and I'm still seeing the same issue:
> 
> ![Image](https://github.com/user-attachments/assets/f0c7d7f5-4349-45c5-ad57-c77c861ea897)
> 
> I'm still using the en_GB dictionary and that dictionary is definitely present in the "/run/host/usr/share/qt6/qtwebengine_dictionaries/" directory. Let me know if there are any specific tests that you'd like me to run.

So it's a dictionary problem.

The test would be to use another dictionary file, since it is now possible to change the dictionary files folder.

**Comment by dymdipii** [comment]
I don't think so because I use the same dictionary system wide and only have issues in zapzap. Here's an example of me using the same dictionary in kwrite but without the false positives:

![Image](https://github.com/user-attachments/assets/f91ceaaa-8202-47dd-89c0-bf8cb2d84ceb)

**Comment by rafatosta** [comment]
Can you locate dictionary files on your system?

 If yes, it tries to change the dictionary standard directory on Zapzap

Post here the format of the files found, please

**Comment by rafatosta** [comment]
Such is using Hunspell himself.

 Zapzap QT6 uses Bir format, while Hunspell DIC. I believe you have some relationship. I will investigate
![Image](https://github.com/user-attachments/assets/fed5f68f-0dec-4039-9a84-32bd541c72b7)

**Comment by rafatosta** [comment]
As ZapZap uses the already compiled format (.bdic) it is possible to obtain it the direct dictionary files of Chromium.

 Here, for pt_br, it worked well. See for you:

https://chromium.googlesource.com/chromium/deps/hunspell/+/9f292621c01a6708cd35416c4482ba5d6881186f/dictionaries

**Comment by dymdipii** [comment]
In the dictionary directory I have bdic dictionaries (this screenshot was taken before my testing):

![Image](https://github.com/user-attachments/assets/89cd2707-7201-420f-a950-6b9137d9254f)

![Image](https://github.com/user-attachments/assets/0f50d7d9-8f34-43aa-b50a-37ae300fb6db)

I tried putting the aff and dic files from the link you provided and reloading zapzap, both the beta and non-beta versions but the spellcheck behaviour was the same

**Comment by dymdipii** [comment]
This is now working for me. I haven't made any changes. I assume it was resolved in an update. Thanks

**Comment by glynhudson** [comment]
I'm still having this issue with 6.3.4.1 

<img width="583" height="237" alt="Image" src="https://github.com/user-attachments/assets/7ee42b54-1a52-4199-8e20-822618ff87ee" />

Any ideas how I can debug?
